package ru.icc.cells.ssdc

import ru.icc.cells.ssdc.model.*
import ru.icc.cells.ssdc.model.style.*

rule "#1" salience -1 no-loop true
    when
        $c : CCell( ( rt == 1 && cl > 1 ) || ( cl == 1 && rt > 1 ) )
    then
        insert ( $c.newLabel() );
        update ( $c );
end

rule "#2" salience -2 no-loop true
    when
        $c : CCell( cl != 1, rt != 1 )
    then
        insert ( $c.newEntry() );
        update ( $c );
end

rule "#3" salience -3 no-loop true
    when
        $c : CCell( containsLabel(), rt == 1, $l : label )
    then
        $l.setCategory( "A" );
        update ( $l );
end

rule "#4" salience -4 no-loop true
    when
        $c : CCell( containsLabel(), cl == 1, $l : label )
    then
        $l.setCategory( "B" );
        update ( $l );
end

rule "#5" salience -5 no-loop true
    when
        $c1 : CCell( containsLabel() )
        $c2 : CCell( containsEntry(), rt == $c1.rt || cl == $c1.cl )
    then
        $c2.getEntry().addLabel( $c1.getLabel() );
end